import React from "react";
import { useRouter } from 'next/router';
import Link from "next/link";
import ProjectSlider from "../components/ProjectSlider";
import {BsGithub} from 'react-icons/bs';

import HTML from "../public/images/programminglogos/html.svg";
import CSS from "../public/images/programminglogos/css.svg";
import JS from "../public/images/programminglogos/javascript.svg";
import Nextjs from "../public/images/programminglogos/next.svg";
import Reactjs from "../public/images/programminglogos/react.svg";
import Laravel from "../public/images/programminglogos/laravel.svg";
import Bootstrap from "../public/images/programminglogos/bootstrap.svg";
import Node from "../public/images/programminglogos/nodes.svg";
import Express from "../public/images/programminglogos/express.svg";
import SocketIO from "../public/images/programminglogos/socket.svg";

import Head from 'next/head';
import {allProjects} from '../projects'; 


export default function Project({projectData}:any) {
    const router=useRouter();
  return (
    <>
      <Head>
        <title>Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className="min-w-[300px] bg-black px-10 lg:absolute lg:top-0 lg:left-0 border-b-2 border-l-gray-100 lg:border-b-0">
          <Link href="/" className="logoContainer inline-block">
              <p className="logo">
                  <span>A</span>
                  <span className="logoA">A</span>
              </p>
          </Link>
      </header>
      <main className="min-w-[300px] h-full pt-10 pb-20 sm:py-20 sm:px-20 lg:px-40 xl:px-72 2xl:px-[20rem] 3xl:px-[40rem] bg-black overflow-x-hidden">
          <div className="mb-5 flex justify-end lg:justify-start mr-2 sm:mr-0 3xl:mb-10">
              <button onClick={() => router.back()} className="bg-darkGray text-white px-6 py-2 rounded text-2xl 3xl:px-10 3xl:py-4 3xl:text-4xl">Back</button>
          </div>
          <ProjectSlider images={projectData.images}/>
          <div className="flex gap-4 mb-4">
              <a href={projectData.liveSite} target="_blank" rel="noopener noreferrer" className="bg-darkGray w-1/2 py-4 hover:cursor-pointer flex justify-center 3xl:py-8">
                  <p className="text-white self-center text-xl 3xl:text-5xl">Live Site</p>
              </a>
              <a href={projectData.github} target="_blank" rel="noopener noreferrer" className="bg-darkGray w-1/2 py-4 hover:cursor-pointer flex justify-center 3xl:py-8">
                  <div className="flex">
                      <p className="text-white self-center mr-2 text-xl 3xl:text-5xl">Github</p>
                      <div className="w-full flex justify-center self-center">
                          <BsGithub className="w-8 h-8 fill-white 3xl:h-12 3xl:w-12"/>
                      </div>
                  </div>
              </a>
          </div>
          <div className="flex flex-col justify-between md:flex-row px-4 md:px-0">
              <h1 className="text-white text-2xl md:text-3xl font-semibold md:self-center mb-4 3xl:text-5xl">{projectData.project}</h1>
              <section className="flex flex-wrap gap-2 mb-4">
                  {projectData.technologies.map((tech:string,index:number)=>{
                      if(tech=="html5"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <HTML className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="css"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <CSS className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="javascript"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <JS className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="next.js"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <Nextjs className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="react.js"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <Reactjs className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="laravel"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <Laravel className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="bootstrap"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <Bootstrap className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="node.js"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <Node className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="express.js"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <Express className="w-10 h-10"/>
                      </div>);
                      }
                      else if(tech=="socketio"){
                          return (<div key={index} className="relative rounded p-2 bg-white">
                          <SocketIO className="w-10 h-10"/>
                      </div>);
                      }
                  })}
              </section>
          </div>
          <div className="px-4 md:px-0">
              <h2 className="text-white text-2xl md:text-2xl xl:text-2xl 3xl:text-5xl mb-4">Description:</h2>
              <p className="text-white text-lg md:text-lg xl:text-xl 3xl:text-3xl">{projectData.description}</p>
          </div>
      </main>
    </>
  );
}


export async function getStaticPaths() {
  const paths=[
        {
            params: {
              id: 'stocktracker'
            }
        },
        {
            params: {
              id: 'postage'
            }
        },
        {
            params: {
              id: 'pixelArt'
            }
        },
        {
            params: {
              id: 'planets'
            }
        },
        {
            params: {
              id: 'tictactoe'
            }
        },
        {
            params: {
              id: 'ecommerceProductPage'
            }
        },
        {
            params: {
              id: 'manage'
            }
        },
        {
            params: {
              id: 'fylo'
            }
        },
        {
            params: {
              id: 'loopstudios'
            }
        },
        {
            params: {
              id: 'pingLaunchingSoon'
            }
        },
        {
            params: {
              id: 'mentorTestimonials'
            }
        },
        {
            params: {
              id: 'sunnysideAgency'
            }
        },
    ];
    return {
        paths,
        fallback:false
    };
}

export async function getStaticProps({ params }:any) {
  let projectData=null;
  for(var i=0; i<allProjects.length;i++){
    if(allProjects[i].name.toLowerCase()===params.id.toLowerCase()){
        projectData=allProjects[i];
    }
  }

  return {
    props: {
        projectData,
    }
  }
}

